### ISSUE TITLE
remaming STATIC file channels

### ISSUE THREAD

**Issue by philjrenaud** [PhilD001/the-zoosystem#2]
Hi,

I am trying to rename channels in the STATIC trial in order to remove the static angle offsets for the dynamic skating trials. However when I run the bmech_renamechannel code, which call the renamech code, I get the following error:

och_pos = {'LAA_static','LEA_static','LHA_static','LKA_static','LPA_static','RAA_static','REA_static',...
           'RHA_static','RKA_static','RPA_static','THA_static'};
nch_pos = {'LAA','LEA','LHA','LKA','LPA','RAA','REA','RHA','RKA','RPA','THA'};

bmech_renamechannel(och_pos,nch_pos,fld)
 
renaming the following channels:
renaming LAA_static to LAA
renaming LEA_static to LEA
renaming LHA_static to LHA
renaming LKA_static to LKA
renaming LPA_static to LPA
renaming RAA_static to RAA
renaming REA_static to REA
renaming RHA_static to RHA
renaming RKA_static to RKA
renaming RPA_static to RPA
renaming THA_static to THA
 
80  for i = 1:length(fl)
renaming channels for: \data\rename static ch test\female\P02\VAPSTATIC01.zoo
Reference to non-existent field 'Analog'.

Error in renamech (line 47)
ach = data.zoosystem.Analog.Channels;

Error in bmech_renamechannel (line 83)
    data = renamech(data,och,nch);

This code does work, if you remember, to rename the 'Acceler' channel to 'Accel', whereby the Analog channel returns an empty 0x0 cell,

this is where the code breaks down when I try to rename the STATIC trial channels. Giving me the "Reference to non-existent field 'Analog'. " error,

thanks for the help!

**Comment by PhilD001** [comment]
The static files only have 'video' data so the call to 'renamech.m' resulted in an error. 'bmech_renamechannel.m' was updated to call the new subfunction 'renamechannel.m' which checks content of file for any existing video or analog data (if available).

The latest zoosystem update contains the new 'bmech_renamechannel.m' and 'renamechannel.m' . 'renamech' was removed as is now obsolete.
